"""Initial schema setup

Revision ID: 9ac39e1a6db1
Revises: 
Create Date: 2026-07-16 16:51:14.648420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac39e1a6db1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('symptoms', sa.String(length=2000), nullable=False),
    sa.Column('causes', sa.String(length=2000), nullable=False),
    sa.Column('severity_level', sa.String(length=50), nullable=False),
    sa.Column('reference_image_url', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diseases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diseases_name'), ['name'], unique=True)

    op.create_table('fertilizers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('composition', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=255), nullable=False),
    sa.Column('application_stage', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fertilizers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fertilizers_id'), ['id'], unique=False)

    op.create_table('pesticides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active_ingredient', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=255), nullable=False),
    sa.Column('application_method', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pesticides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pesticides_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('farm_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('disease_fertilizer',
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('fertilizer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fertilizer_id'], ['fertilizers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('disease_id', 'fertilizer_id')
    )
    op.create_table('disease_pesticide',
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('pesticide_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pesticide_id'], ['pesticides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('disease_id', 'pesticide_id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=False),
    sa.Column('pesticide_id', sa.Integer(), nullable=True),
    sa.Column('fertilizer_id', sa.Integer(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fertilizer_id'], ['fertilizers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pesticide_id'], ['pesticides.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_id'), ['id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_id'))

    op.drop_table('reports')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_id'))

    op.drop_table('recommendations')
    op.drop_table('predictions')
    op.drop_table('disease_pesticide')
    op.drop_table('disease_fertilizer')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('pesticides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pesticides_id'))

    op.drop_table('pesticides')
    with op.batch_alter_table('fertilizers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fertilizers_id'))

    op.drop_table('fertilizers')
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diseases_name'))
        batch_op.drop_index(batch_op.f('ix_diseases_id'))

    op.drop_table('diseases')
    # ### end Alembic commands ###
